### ISSUE TITLE
Empty GridView

### ISSUE THREAD

**Issue by LinkeyWork** [ceryle/FitGridView#2]
How Can I set the fitgridview empty before loading data from internet?

`FATAL EXCEPTION: main
Process: app.comp.fly, PID: 30443
 java.lang.ArithmeticException: divide by zero
 at co.ceryle.fitgridview.FitGridView.remeasure(FitGridView.java:95)
 at co.ceryle.fitgridview.FitGridView.update(FitGridView.java:66)
at co.ceryle.fitgridview.FitGridView.setFitGridAdapter(FitGridView.java:121)
at app.comp.fly.Fragments.ServicesFragment.initGridView(ServicesFragment.java:52)
at app.comp.fly.Fragments.ServicesFragment.onCreateView(ServicesFragment.java:44)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                  at android.os.Handler.handleCallback(Handler.java:733)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:136)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                  at dalvik.system.NativeStart.main(Native Method)`

**Comment by ceryle** [comment]
Hi, you can set fitgridview empty now. However do not forget setting row and column values before setting adapter.
Ex:
        gridView.setColumn(5);
        gridView.setRow(5);
        gridView.setFitGridAdapter(new Adapter(this));

**Comment by aitbaali** [comment]
I've solved the emptiness state by changing some of your code:

> **FitGridView

`
private void remeasure() {
        itemWidth = getMeasuredWidth() / (column == 0 ? 1 : column);
        itemHeight = getMeasuredHeight() / (row == 0 ? 1 : row);
    }
`

can now create empty grid without providing number of columns/rows

**Comment by ceryle** [comment]
Hi aitbaali,
It seems your solution is more logical than mine, because someone may want to give only row or column. I will update the library right now.
